language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t klin7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true klin7/react-test npm test

after_success:
  - docker build -t klin7/multi-client ./client
  - docker build -t klin7/multi-nginx ./nginx
  - docker build -t klin7/multi-server ./server
  - docker build -t klin7/multi-worker ./worker
  # Login to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  # Take those image and push those to docker hub

  - docker push klin7/multi-client
  - docker push klin7/multi-nginx
  - docker push klin7/multi-server
  - docker push klin7/multi-worker
  
  
  
  